{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.linlishui",
    "module": "android-base",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-base-0.0.1.aar",
          "url": "android-base-0.0.1.aar",
          "size": 26246,
          "sha512": "857120dd2d40b2e0ffe211bb14b2106596dde1996ff5473138739efdae23bfb8b11b9c1fc02f413630b9a700f626c127c8e751d9eb494a2b709036f8279c9904",
          "sha256": "c4bdd44b130aced6f37e0d84c579083c8249fae61a01022756ff819a55d347e5",
          "sha1": "edce07087e02e507106e563b36b922e00cf1dc58",
          "md5": "d4abb8d99ced7fed3b2190b795364721"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "android-base-0.0.1.aar",
          "url": "android-base-0.0.1.aar",
          "size": 26246,
          "sha512": "857120dd2d40b2e0ffe211bb14b2106596dde1996ff5473138739efdae23bfb8b11b9c1fc02f413630b9a700f626c127c8e751d9eb494a2b709036f8279c9904",
          "sha256": "c4bdd44b130aced6f37e0d84c579083c8249fae61a01022756ff819a55d347e5",
          "sha1": "edce07087e02e507106e563b36b922e00cf1dc58",
          "md5": "d4abb8d99ced7fed3b2190b795364721"
        }
      ]
    }
  ]
}
